import { expect, test } from '@playwright/test'

test('model prices show peak, off-peak and long-context tiers', async ({ page }) => {
  const modelName = `gpt-peak-e2e-${Date.now()}`
  await page.request.post('/api/auth/setup', { data: { username: 'admin', password: 'test-password', nickname: 'Admin' } })
  await page.goto('/login')
  const inputs = page.locator('input')
  await inputs.nth(0).fill('admin')
  await inputs.nth(1).fill('test-password')
  if ((await inputs.count()) >= 3) await inputs.nth(2).fill('管理员')
  await page.locator('button[type="submit"]').click()
  await page.waitForURL(/\/admin\/usage/)

  await page.goto('/admin/pricing')
  await page.getByRole('button', { name: /新增价格|Add price/ }).click()
  const dialog = page.getByRole('dialog', { name: /新增价格|Add price/ })
  await dialog.locator('#price-provider').fill('openai')
  await dialog.locator('#price-model').fill(modelName)
  await dialog.locator('#price-input').fill('1')
  await dialog.locator('#price-output').fill('4')
  await dialog.getByRole('switch', { name: /支持 FAST 模式|Supports FAST mode/ }).click()
  await dialog.locator('#price-fast-multiplier').fill('2')
  await dialog.getByRole('switch', { name: /启用长上下文费率|Enable long-context rates/ }).click()
  await expect(dialog.getByRole('switch', { name: /长上下文支持 FAST 模式|FAST mode available for long context/ })).toBeVisible()
  await dialog.locator('#price-long-context-threshold').fill('100')
  await dialog.locator('#price-long-context-input').fill('3')
  await dialog.getByRole('switch', { name: /启用峰谷分段计费|Enable peak\/off-peak pricing/ }).click()
  await dialog.locator('#price-peak_input_usd_per_million').fill('2')
  await dialog.locator('#price-long_context_peak_input_usd_per_million').fill('6')
  await dialog.getByRole('button', { name: /保存|Save/ }).click()

  const row = page.getByRole('row').filter({ hasText: modelName })
  await expect(row).toHaveCount(1)
  const tiers = row.getByRole('cell').nth(2)
  await expect(tiers).toContainText(/常规 · 高峰|Standard · peak/)
  await expect(tiers).toContainText(/常规 · 空闲|Standard · off-peak/)
  await expect(tiers).toContainText(/长上下文 · 高峰|Long context · peak/)
  await expect(tiers).toContainText(/长上下文 · 空闲|Long context · off-peak/)
  await expect(tiers.locator('.rate-tier-line')).toHaveCount(8)
  await expect(tiers).not.toContainText('×2')
  await expect(row.getByRole('cell').nth(4).locator('.rate-tier-line')).toHaveText(['1', '2', '2', '4', '3', '6', '6', '12'])
  await expect(row.getByRole('cell').nth(4)).toContainText('2')
  await expect(row.getByRole('cell').nth(4)).toContainText('4')
  await expect(row.getByRole('cell').first()).not.toContainText(/长上下文|Long context/)
  const actionsButton = row.getByRole('button', { name: /打开.*操作菜单|Open actions/ })
  await expect(actionsButton).toBeVisible()
  await expect(row.getByRole('button', { name: /改价|Edit/ })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: /更新|Updated/ })).toHaveCount(0)
  const tableContainer = page.locator('.price-table > [data-slot="table-container"]')
  for (const width of [1366, 1280, 1024]) {
    await page.setViewportSize({ width, height: 1000 })
    const dimensions = await tableContainer.evaluate((element) => ({ scrollWidth: element.scrollWidth, clientWidth: element.clientWidth, tableWidth: element.querySelector('table')?.getBoundingClientRect().width }))
    expect(dimensions.scrollWidth > dimensions.clientWidth, `table overflow at ${width}px: ${JSON.stringify(dimensions)}`).toBe(false)
    const editBox = await actionsButton.boundingBox()
    const containerBox = await tableContainer.boundingBox()
    expect(editBox && containerBox && editBox.x + editBox.width <= containerBox.x + containerBox.width + 1).toBe(true)
  }

  await actionsButton.click()
  await page.getByRole('menuitem', { name: /编辑|Edit/ }).click()
  const editDialog = page.getByRole('dialog', { name: /编辑价格|Edit price/ })
  await editDialog.getByRole('switch', { name: /长上下文支持 FAST 模式|FAST mode available for long context/ }).click()
  await editDialog.getByRole('button', { name: /保存|Save/ }).click()
  await expect(row.getByRole('cell').nth(2).locator('.rate-tier-line')).toHaveCount(6)

  await actionsButton.click()
  await page.getByRole('menuitem', { name: /编辑|Edit/ }).click()
  await editDialog.getByRole('switch', { name: /支持 FAST 模式|Supports FAST mode/ }).click()
  await expect(editDialog.locator('#price-fast-multiplier')).toHaveCount(0)
  await expect(editDialog.getByRole('switch', { name: /长上下文支持 FAST 模式|FAST mode available for long context/ })).toHaveCount(0)
  await editDialog.getByRole('button', { name: /保存|Save/ }).click()
  await expect(row.getByRole('cell').nth(2).locator('.rate-tier-line')).toHaveCount(4)

  await page.getByRole('button', { name: /节假日日历|Holiday calendar/ }).click()
  const calendar = page.getByRole('dialog', { name: /峰谷计费节假日日历|Peak pricing holiday calendar/ })
  await expect(calendar.getByRole('row').filter({ hasText: '2026-09-25' })).toContainText(/休息日|Off-day/)
  await expect(calendar.getByRole('row').filter({ hasText: '2026-09-20' })).toContainText(/调休上班|Makeup workday/)
  const makeupSwitch = calendar.getByRole('switch', { name: /调休日按高峰价计算|Charge peak rates on makeup workdays/ })
  if (!(await makeupSwitch.isChecked())) await makeupSwitch.click()
  await calendar.getByRole('button', { name: /添加时段|Add period/ }).click()
  await expect(calendar.locator('input[type="time"]')).toHaveCount(6)
  await calendar.getByRole('button', { name: /删除第 3 段|Remove period 3/ }).click()
  await calendar.getByRole('textbox', { name: /第 1 段开始时间|Period 1 start/ }).fill('08:30')
  await calendar.getByRole('button', { name: /保存选项|Save setting/ }).click()
  await page.getByRole('button', { name: /节假日日历|Holiday calendar/ }).click()
  await expect(calendar.getByRole('switch', { name: /调休日按高峰价计算|Charge peak rates on makeup workdays/ })).toBeChecked()
  await expect(calendar.getByRole('textbox', { name: /第 1 段开始时间|Period 1 start/ })).toHaveValue('08:30')
})
